# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Pod-WSDL-Method
version:      0.02
version_from: lib/Pod/WSDL/Method.pm
installdirs:  site
requires:
    Pod::WSDL::AUTOLOAD:           0.01
    Pod::WSDL::Doc:                0.01
    Pod::WSDL::Fault:              0.01
    Pod::WSDL::Param:              0.01
    Pod::WSDL::Return:             0.01
    Pod::WSDL::Utils:              0.01
    Pod::WSDL::Writer:             0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
